name: Deploy config to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - "config/host.txt"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare dist
        run: |
          mkdir -p dist/config
          cp config/host.txt dist/config/host.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
